### ISSUE TITLE
The projections on Indian sword pommels

### ISSUE THREAD

**Issue by PsMonkey** [PsMonkey/ColdWeapon#10]
https://www.youtube.com/watch?v=d92iCDIgcyw

**Comment by ycliunpm** [comment]
* 關於印度劍柄 pommel 上凸出物的作用，
作者列出幾種常見說法：
    1. 當劍未出鞘時，
        可安置手掌之處。
    2. 可用來安置坐騎的韁繩。
        但作者不曉得如何操作。
    3. 攻擊對手。
    4. 可讓另一隻手抓握，
        以加強攻擊力道。
    5. 可保護手腕(前臂下方部位)。
* 除了對前兩項沒有概念外，作者對於其他說法有些意見：
    1. 關於讓雙手可以抓握之說，
        16、17世紀印度、波斯繪畫中顯示使用者的確會使用雙手抓握 pommel部位。
        但作者認為此說法的問題在於，
        許多劍的凸出物是以金屬薄片製成，
        多呈現中空狀態，
        而且經常只是黏附於劍柄上，
        並不牢固。
        若用力攻擊對手，
        此部位可能會斷裂。
    2. 若要保護手腕，
       作者認為其強度與長度皆不足。
    3. 因印度劍柄 pommel 凸出物經常以球形呈現，
       若真要攻擊對手，
       理應設計成較尖銳造型，
       也不會讓此部分中空。
* 作者傾向於認為印度劍柄 pommel 凸出物可能同時具備多種用途，
       既可以攻擊對手、
       或許也跟佩戴劍的方式相關。
* 作者提到曾看過某些 talwar 劍柄凸出物有穿孔，
       可以繫繩或綁流蘇。
       穿繩或許是確保即便劍柄脫離使用者手掌，
       使用者仍可輕易將其取回。
* 有些印度劍柄 pommel 凸出物較長，
       也相當彎曲，
       因此若要攻擊對手似乎不大合理。
       綜合以上，
       作者尚無法明確推斷此物用途。
* Talwar 劍柄 pommel 偶而會有較長凸出物，
       但18世紀時開始變短，
       到19世紀時造型變得相當尖銳。
* 以下為另一個關於印度劍柄 pommel 凸出物用途較具說服力的說法：
       它可勾住並撥開對手的盾牌 (shield) 或圓盾 (buckler)。
       印度當時經常於戰鬥中使用盾牌，
       若能撥開對手盾牌，
       即可接續以劍刃進行攻擊。
       但若這便是此物原本的用途，
       作者仍無法解釋此部位為何未設計得更扎實或更尖銳。

**Comment by PsMonkey** [comment]
# Must Answer #

* 這篇是不是沒有專指 talwar、而是理論上講所有的印度劍（只是剛好 talwar 講得多了點？）。
    * 我先假設這個問題的答案是「yes」
* talwar 有可能「許多突出物是以金屬薄片製成，因此呈現中空狀態，而且經常只是黏附於劍柄上，並不牢固。」嗎？一般圖片很少從側面（鏡頭對準刀刃尖端）照，只是有那個 disc 我實在很難想像要怎符合這句？


# Fix or Answer #

* [Yahoo 字典] 說 projection 也有「設計 / 規劃」的意思。我不太確定就英文文法來說「設計」跟「凸出物」哪個比較合適。但是... 相對於整把劍而言，pommel 本身就是凸出物.... 吧？凸出物上的凸出物感覺很奇怪阿.... :scream: 
    * 然後雖然教育部的國語字典看不太出兩者差異，不過 [Yahoo 字典]還有[對岸知乎](https://www.zhihu.com/question/28534767)都傾向「凸出」（如果這裡真的是凸出的意思），所以請改用「凸出」
* > 16、17繪畫中顯示使用者的確會使用雙手抓握 pommel部位。

    這什麼鬼？ 16、17 世紀？
* > 部分劍柄的突出物有個穿孔......

    我沒聽錯的話（[5:50](https://youtu.be/d92iCDIgcyw?t=351)，這部份是專講 talwar 吧？然後你這段寫得很詭異，後半段

    > 有些突出物較長，也相當彎曲，因此若要攻擊對手似乎不大合理。

    這跟前面穿孔的已經壓根看不出什麼關聯。我覺得有高達 94.87% 的機率是作者錄的時候突然跳 tone 了一下然後你就乖乖用逐字稿的寫法跟著寫了？
* > 作者另外提到兩點：

    不要老是用逐字稿的寫法來寫... 就論點脈絡上來看，第二點根本沒有什麼「另外」可言。

[Yahoo 字典]: https://tw.dictionary.search.yahoo.com/search?p=projection

**Comment by ycliunpm** [comment]
* >  這篇是不是沒有專指 talwar、而是理論上講所有的印度劍（只是剛好 talwar 講得多了點？）。

是。

* > talwar 有可能「許多突出物是以金屬薄片製成，因此呈現中空狀態，而且經常只是黏附於劍柄上，並不牢固。」嗎？一般圖片很少從側面（鏡頭對準刀刃尖端）照，只是有那個 disc 我實在很難想像要怎符合這句？

此處僅指 talwar 劍柄頂端的凸出部位。
已修改寫法。
* >  我沒聽錯的話（[5:50](https://youtu.be/d92iCDIgcyw?t=351)，這部份是專講 talwar 吧？


 作者一開始以 talwar 為例，之後就改用 sword 了。

**Comment by PsMonkey** [comment]
「Fix or Answer」是要嘛你改、要嘛你回答。而你並沒有回答第一個「到底翻譯為『凸出』還是『設計』」。你不能來個「反正我沒改就是回答你了」，因為我不知道你到底是不打算改還是沒看到。

然後基本上你越改越糟糕。之前的版本只是文意有點詭異跟矛盾，現在這個版本（v3）則是根本看不出你在寫什麼。

你要記得，你寫這些的目的是給「沒看過影片的人看的」，讓他們（包含未來的你）即使不用看影片也能知道這部影片的核心重點、而不用花時間去看 ~~閃亮的光頭晃來晃去~~完整個影片。

所以：

# Fix or Answer #

> 作者傾向於認為此凸出物可能同時具備多種用途，
> 既可以攻擊對手、
> 或許也跟佩戴劍的方式相關。

何謂「此凸出物」？你要說的是「所有（印度劍）的 pommel 凸出物」（那就不應該加「此」）？還是作者拿某把劍當範例（那你乾脆直接作個帶時間的 YouTube 連結）？

同樣的：

> 另一個關於其用途較具說服力的說法是：
> 它可勾住並撥開對手的盾牌 (shield) 或圓盾 (buckler)。
> 印度當時經常於戰鬥中使用盾牌，

這裡的「其用途」是「所有（印度劍）的 pommel 凸出物」還是「talwar 的凸出物」？雖然我在第一次 comment 已經吐嘈這應該不是在講 talwar，但是你目前版本的上下文還是會讓人覺得這是在講「talwar 的凸出物」

# just murmur #

我現在大概也看過數百張 talwar 或著說反正就是有 disc 的劍柄（當然有可能有重複啦），我還沒看過有搞穿孔的....

另外，我壓根覺得這個影片太零散片段，不是很有參考價值。你解決完上面問題之後我會重整 / 重寫一次，看看能不能有比較好得結果.......

**Comment by ycliunpm** [comment]
* > Yahoo 字典 說 projection 也有「設計 / 規劃」的意思。我不太確定就英文文法來說「設計」跟「凸出物」哪個比較合適。但是... 相對於整把劍而言，pommel 本身就是凸出物.... 吧？凸出物上的凸出物感覺很奇怪阿.... 😱
然後雖然教育部的國語字典看不太出兩者差異，不過 Yahoo 字典還有對岸知乎都傾向「凸出」（如果這裡真的是凸出的意思），所以請改用「凸出」


確定採用「凸出」。


* > 何謂「此凸出物」？你要說的是「所有（印度劍）的 pommel 凸出物」（那就不應該加「此」）？還是作者拿某把劍當範例（那你乾脆直接作個帶時間的 YouTube 連結）？

指「所有（印度劍）的 pommel 凸出物」。已改。



* > 這裡的「其用途」是「所有（印度劍）的 pommel 凸出物」還是「talwar 的凸出物」？雖然我在第一次 comment 已經吐嘈這應該不是在講 talwar，但是你目前版本的上下文還是會讓人覺得這是在講「talwar 的凸出物」

指「所有（印度劍）的 pommel 凸出物」。上下文已改。
