### ISSUE TITLE
看完《英國人與 tulwar》

### ISSUE THREAD

**Issue by PsMonkey** [PsMonkey/ColdWeapon#12]
我翻譯成中文了： http://blog.psmonkey.org/2019/05/tulwar.html

看完之後請直接 close issue。

當然如果你要比對原文考究我的翻譯有沒有問題，也是非常歡迎，請留 comment 詰譙...... [擺茶點]

**Comment by ycliunpm** [comment]
*  > 在喬治王與維多利亞時代，印度的景觀、聲音、氣味讓許多曾在那裡服役或是拜訪過的英國人感到癡迷。

建議譯為： 「印度的景觀、聲音、氣味，讓許多曾於喬治與維多利亞時代造訪或在那裡服役過的英國人感到癡迷。」


*  >這把 curiously-hilted 劍 

建議譯為： 這把柄部形制奇特的劍
