### ISSUE TITLE
冷兵器閱讀摘要

### ISSUE THREAD

**Issue by ycliunpm** [PsMonkey/ColdWeapon#3]
*Islamic Arms and Armor: in The Metropolitan Museum of Art*
導論敘述大都會兵器館藏歷史、各藏家收藏特色。各單品說明分3部分：

1. 外觀描述
1. 款識內容翻譯
1. 文物背景歷史介紹

**Comment by ycliunpm** [comment]
scholagladiatoria Youtube: "[Medieval dagger grips, defending against sword and blade length](https://www.youtube.com/watch?v=mToGc2RM3kA)"
XX(某本歐洲書?)如何介紹以中世紀匕首抵擋劍的攻擊。當匕首刃部與前臂等長，反手持拿匕首可用來遮蔽劍的攻勢，因而推論某些匕首刃部長度與人體前臂長度相關。但並非所有匕首皆然。

**Comment by ycliunpm** [comment]
scholagladiatoria Youtube: ["Different ways that sword hilts are attached to sword blades."](https://www.youtube.com/watch?v=XUL80bbJMOI&t=203s)

- 不同類型的劍之刃部與柄部有不同連接方式。中世紀劍的tang(刃部底端與柄部連結部位)長度長於柄部，因此會從柄部頂端突出，再以彎折、壓扁等方式固定於柄部。

- 日本劍tang通常寬扁，短於柄部，會有2-3個洞。會有竹製樁(peg?)穿過，將tang固定於柄部內。傳統日本劍的tang不會長於柄部。
- 有些歐洲劍固定tang的方式類似於knife，是以刃部的兩片板將tang夾於中間，並以填滿孔洞方式固定。
- 許多亞洲劍、刀、大刀完全不用以上方式，而採黏合方式。在柄部熱時，填滿類似焦油(tar?)之深色物質，再將tang塞進去固定，幾乎到達pommel部位。時日久後膠開始會老化，導致柄部開始鬆動。印度、東南亞部分地區、尼泊爾、中東地區都有此作法。

**Comment by ycliunpm** [comment]
Alexander, David G., with contributions by Stuart W. Pyhrr, and Will Kwiatkowski,
*Islamic Arms and Armor: in The Metropolitan Museum of Art* (Metropolitan Museum of Art, 2016)

**Comment by PsMonkey** [comment]
基本上一個 issue 只處理一件事情，這個 issue 包含了三件事...... :scream:
