### ISSUE TITLE
scholagladiatoria Youtube: Asian influence on antique British military swords

### ISSUE THREAD

**Issue by ycliunpm** [PsMonkey/ColdWeapon#4]
scholagladiatoria Youtube: [Asian influence on antique British military swords](https://www.youtube.com/watch?v=Fng9BFgYGog)
* 大英帝國於殖民時代接觸許多不同異文化，也影響到兵器的發展。1800年的英國步兵團會軍官雖配有標準規格的劍(spadroon)，但許多人因為品味、喜好、或實際戰鬥使用...等因素考量，會另用其他兵器，如騎兵(calvary)使用的軍刀(sabre)，因而產生許多非標準(non-regulation)劍。
* 在印度、非洲、阿富汗等地區，因較常需要近距離搏鬥，許多軍官會選擇較堅固且更有競爭力的兵器，印度tulwar就是一例。
* 第1把劍刃部與印度tulwar明顯相似，柄部卻為英國標準長劍型制。第2把劍年代較晚(約1810-1820)，柄部是當時典型英國長劍型制(steer up hilt?)，但刃部卻與前一把長劍相同，在造型、做工上與印度tulwar柄部相似。第2把劍刃上的fuller(?)/groove設計可減輕刃部重量並增強硬度；刃部上幾個間斷性長方型凹槽(fuller?)為印度/波斯地區長劍特徵。雖然此劍刃部有可能來自印度tulwar，但Eason因為某些未說明的理由認為這把劍應該全屬英國作工，劍鞘亦然。

**Comment by PsMonkey** [comment]
[第 1 把劍](https://youtu.be/Fng9BFgYGog?t=198) 應該就是標準 tulwar，他的劍柄看不出什麼英國風格（可參考[另外一個專講 tulwar 的影片](https://youtu.be/2BoKUfaorJ0?t=25)，應該是同一把劍）。用上下文來看也很奇怪，如果兩把都是英國改造版，這樣對比有啥意義？ :see_no_evil: 

然後你一直打問號的 fuller 沒有拼錯、是專有名詞，參見 [wikipedia](https://en.wikipedia.org/wiki/Fuller_(weapon))，如果你沒其他意見我就會把你的問號都刪掉。（雖然我本來就會改你的文字 :dancer: ）

請 confirm

**Comment by ycliunpm** [comment]
* 大英帝國於殖民時代接觸許多不同異文化，也影響到兵器的發展。1800年的英國步兵團會軍官雖配有標準規格的劍(如spadroon)，但許多人因為品味、喜好、或實際戰鬥使用...等因素考量，會另用其他兵器，如騎兵(calvary)使用的軍刀(saber)，因而產生許多非標準(non-regulation)劍。
* 在印度、非洲、阿富汗等地區，因較常需要近距離搏鬥，許多軍官會選擇較堅固且更有競爭力的兵器，印度tulwar就是一例。
* 第1把劍為印度tulwar，第2把劍年代較晚(約1810-1820)，柄部是當時典型英國長劍柄部常見造型，但刃部造型、弧度、重量、厚度皆與印度tulwar相似。
* 雖然第2把劍刃上的凹槽(fuller/groove)設計與第一把tulwar不同，但凹槽形式本來就有很多種。凹槽可減輕刃部重量並增強硬度；刃部上幾個間斷性長方型凹槽為印度/波斯地區長劍特徵。雖然此劍刃部有可能自某把印度tulwar嫁接而來，但Eason因為某些未說明的理由認為這把劍應該全屬英國作工，劍鞘亦然(未於影片顯示劍鞘)。

疑問：Eason為何認為第2把劍屬英國作工，值得探究。

**Comment by PsMonkey** [comment]
補個一刀，這傢伙叫做  Matt Easton，不是 Eason
