### ISSUE TITLE
Tulwars! The typical Indian sword, famed for its awesome cutting power

### ISSUE THREAD

**Issue by ycliunpm** [PsMonkey/ColdWeapon#5]
* Tulwar基本上就是一種saber，在印度、尼泊爾、阿富汗與現今巴基斯坦等地區相當常見。其刃部與歐洲saber相似，甚至經常直接取用歐洲saber的刃部，如18世紀時拿德國saber刃部改裝，19世紀則拿英國saber並將刃部稍作修改，再將之接上tulwar柄部。
* 影片希望澄清幾個tulwar常見的誤解，在D.A. Kinsley的書中亦有說明相關知識。1. 與歐洲劍相比，tulwar柄部相對短；2.通常會有護手(cross guard)，有時雖然有knuckle bow， 但不影響握姿；3. 柄部中段會鼓起，甚至如球狀； 4. 最重要的是柄部頂端的圓碟(disc)設計。
* 與中東地區的shamshir/killick(待查)類似，護手通常扁平，致使握劍時，大拇指可以服貼地靠在護手上，使線條可以齊整(keep the edge aligned?無法理解)。
* 柄部中段隆起處讓手可以握得更緊實。
* 因tulwar柄部實際可以掌握住的長度受制於頂端圓碟，許多人因而推論當時的印度人體型較小。雖然體型較小現象有部分屬實，但多數人是因為營養等其他因素，跟現代人相較之下體型才顯得相對嬌小。此觀點亦使圓碟設計在tulwar上的真正用意被模糊化。它其實是強迫/鼓勵使用者以特定的方式握住柄部。握劍時，若將劍身往前伸(類似歐洲劍的握法)，柄部圓碟就會突兀地戳進手掌。正確握法應該是要讓劍身與手臂儘量呈90度/稍大角度，才能在揮劍時讓刃部外側有更多部分讓對手受傷，如：砍斷對手身體部位、造成大面積傷口、大失血...等。
* 因使用方式使然，tulwar的攻擊範圍不像歐洲劍那樣寬廣，需要在較近距離才能攻擊對手。在馬背上使用tulwar時，可將武器推向(push)對手，與歐洲劍插入(thrust)對手的做法類似，只是tulwar會以刃部外側進行攻擊。D.A. Kinsley書中便有提及如何以tulwar取敵人首級。

**Comment by PsMonkey** [comment]
## 文字面的問題 ##

* 你的第一點真的怎麼看怎麼怪，你確定你沒有誤會作者的意思？
* pommel 到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）
* 你打的（YouTube 字幕提供的）killick，我查了一下應該是 [kilij] 才對，我是不知道這玩意要怎麼發音，不過土耳其文寫作「kılıç」，好像也就不太意外了...... :zzz: 
* 我不確定你的「keep the edge aligned」是哪裡不理解 ~~（橫豎我都不理解 :see_no_evil: ）~~
    如果是 `edge` 這個字的話，可以參見下面幾個影片（Edge & Flat in parring 系列）來望文生義？
    1. https://www.youtube.com/watch?v=ZeDFc2QQ-XU
    1. https://www.youtube.com/watch?v=lyjeBPJVdac
    1. https://www.youtube.com/watch?v=Kysxg6plugc
    1. https://www.youtube.com/watch?v=s8BUJp-5CXY

    第一個影片還是拿 dagger 示範的，你可以優先當作下一個推薦的項目 :dancer: 

[kilij]: https://en.wikipedia.org/wiki/Kilij


## 寫作面的提醒 ##

你的第二點「影片希望澄清幾個tulwar常見的誤解......」，裡頭還有四個子項目，所以你可以寫成

```
* 影片希望澄清幾個tulwar常見的誤解......
    1. 與歐洲劍相比，tulwar柄部相對短；
    1. 通常會有護手(cross guard)，有時雖然有knuckle bow， 但不影響握姿；
    1. 柄部中段會鼓起，甚至如球狀； 
    4. 最重要的是柄部頂端的圓碟(disc)設計。
* 與中東地區的shamshir/killick(待查)......
```

因為是第二層的 list，所以前面要加上（至少兩個）空格來區別（其實我都用 tab，不過 issue 的介面很難輸入 tab...... :sob: ）

然後預防性的提醒一下，如果你要針對我某句話作回應，請用 quote block

**Comment by ycliunpm** [comment]
* Tulwar基本上就是一種saber，在印度、尼泊爾、阿富汗與現今巴基斯坦等地區相當常見。其刃部與歐洲saber相似，甚至經常直接取用歐洲saber的刃部套上tulwar的柄部，如18世紀時拿德國saber刃部，19世紀則拿英國saber刃部稍作修改。
* 作者希望澄清幾個tulwar常見的誤解，在D.A. Kinsley的書中亦有說明相關知識。
  1. 與歐洲劍相比，tulwar柄部相對短；
  2. 通常會有護手(cross guard)，有時雖然有knuckle bow， 但不影響握姿；
  3. 柄部中段會鼓起，甚至如球狀； 
  4. 最重要的是柄部頂端的圓碟(disc)設計。
* 與中東地區的shamshir/killij類似，護手通常扁平，致使握劍時，大拇指可以服貼地靠在護手上，使線條可以齊整(keep the edge aligned)。
* 柄部中段隆起處讓手可以握得更緊實。
* 因tulwar柄部實際可以掌握住的長度受制於頂端圓碟，許多人因而推論當時的印度人體型較小。雖然體型較小現象有部分屬實，但多數人是因為營養等其他因素，跟現代人相較之下體型才顯得相對嬌小。此觀點亦使tulwar上圓碟設計的真正用意被模糊化。它其實是強迫/鼓勵使用者以特定的方式握住柄部。握劍時，若將劍身往前指(類似歐洲劍的握法)，柄部圓碟就會突兀地戳進手掌。正確握法應該是讓劍身與手臂儘量呈90度/稍大角度，揮劍時才能讓刃部外側更多部分去傷及對手，如：砍斷對手身體部位、造成大面積傷口、大失血...等。
* 因使用方式使然，tulwar的攻擊範圍不像歐洲劍那樣寬廣，需要在較近距離才能攻擊對手。在馬背上使用tulwar時，可將其推向(push)對手，與歐洲劍插入(thrust)對手的做法類似，只是tulwar會以刃部外側進行攻擊。D.A. Kinsley書中便有提及如何以tulwar取敵人首級。

**Comment by ycliunpm** [comment]
* > pommel到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）

直覺反應是頂端，但會再優先確認兵器敘述傳統。
* > 我不確定你的「keep the edge aligned」是哪裡不理解

如果字面上理解沒錯的話，不確定其作用為何。會再看你推薦的影片有什麼發現。

**Comment by PsMonkey** [comment]
你這樣我不知道你改了什麼，上次（#4）是因為你根本論述就有問題，所以直接請你重貼一篇。

**現在修正：除非你打算整段砍掉重寫，不然請你直接貼「要改的部份」**，如果我的 comment 提到的諸如名詞用字校正、或是 markdown 格式的部份，只要你同意的話就不用再重複了。

最後，麻煩請你先確認完 pommel 到底算底部還是頂部、還有那個 edge 到底是啥（或是仍然無解）再來重新 comment。

**Comment by ycliunpm** [comment]
> pommel 到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）

此問題目前無解。目前會採取的寫法是儘量直接使用該部位專有名詞(如果有的話)；若要描述該部位上下左右，則附帶描述周圍區域，以利辨別。

> 那個 edge 到底是啥（或是仍然無解）

仍然無解。

**Comment by PsMonkey** [comment]
> # 這個 comment 純粹是針對 markdown 撰寫的部份。 #

------------------------

你在 [這個 comment](https://github.com/PsMonkey/ColdWeapon/issues/5#issuecomment-481091626) 當中寫錯了，你寫的是

```
* > pommel到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）
```

這樣在語意 / 視覺上會是「這個 list 的內容是 quote」，
實際上應該是「你 quote 了一個 list」才比較合理，所以應該寫：

```
> * pommel到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）
```

--------

請善用空白行跟換行，來讓你寫的時候更清楚。
例如同一個 comment，你是這樣寫的

```
* > pommel到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）

直覺反應是頂端，但會再優先確認兵器敘述傳統。
* > 我不確定你的「keep the edge aligned」是哪裡不理解
```

我會這樣寫（甚至空兩行）

```
* > pommel到底算 hilt 的底端還是頂端？（或著問：一把劍怎麼分上下左右？）

直覺反應是頂端，但會再優先確認兵器敘述傳統。

* > 我不確定你的「keep the edge aligned」是哪裡不理解
```

換行的部份可參考 [talwar](https://github.com/PsMonkey/ColdWeapon/blob/master/talwar.md) 條目的[原始 markdown](https://raw.githubusercontent.com/PsMonkey/ColdWeapon/master/talwar.md)。
你會發現我把內容很長的 list 拆成好多行，只要每一行前面用空白鍵（或是 tab）往內 / 右）縮即可。
這除了看起來更不容易累之外，日後要作版本比較也比較方便（[參見這個頁面](https://github.com/PsMonkey/ColdWeapon/commit/ed084afc9130383103067e66fd1203b4db9b79cc#diff-5f3ec301511c0a6de472481a273c3e68)）

對，最後呈現上是不會有差異，搞這些的優點是在撰寫跟後續維護上。

**Comment by PsMonkey** [comment]
光頭最近出了一個新的影片[Medieval Swords: Edge Vs Flat and Sword Hilt Design](https://www.youtube.com/watch?v=48Vd8C0iB7A) ，我有紀錄在 [article.md](https://github.com/PsMonkey/ColdWeapon/blob/master/resource/article.md) 裡。他又重啟了這個 edge / flat 的話題，而且還跟劍柄設計有關。

不過都是傳統長劍.... :sob: 

先 FYI 一下，以防你再次面臨 edge / flat 的問題。

ps. 如果我的英文沒有理解錯誤，光頭在論述上會以 pommel 為劍的底部，主要是因為持刀的姿態，當然這在 dagger 系的可能就會有點詭異 :dancer:
