### ISSUE TITLE
Tulwars/talwars - Indian swords and swordsmanship, part 2

### ISSUE THREAD

**Issue by PsMonkey** [PsMonkey/ColdWeapon#7]
https://www.youtube.com/watch?v=7BjjtGEvvvo

--------

# 作業流程變更 #

1. 請將「內文」直接在這個 issue 下頭寫 comment，不要再新開 issue
2. 如果後續要修正「內文」，直接修改該 comment，修改完畢之後另外寫一個 dummy comment 讓系統通知我有 update

**Comment by PsMonkey** [comment]
重新定義「作業流程」，順便示範何謂 dummy comment（對，這個 comment 就是讓系統通知你用的）

**Comment by ycliunpm** [comment]
* 使用talwar時運用的肌肉與使用歐洲劍時不同，
歐洲劍多靠手腕的力道去控制，
talwar則會運用上臂、肩膀、背部大塊肌肉，
也會因上半身與臀部轉動動作使攻擊力道更為強大。
雖然talwar的攻擊範圍比較小，
致使使用者必須較接近對手才能進行攻擊，
但一旦攻擊則極具殺傷力。
* 作者觀察各博物館收藏（如Wallace collection,V &A collection）時發現，
較昂貴與使用者地位較高的tulwar，
其柄部似乎較一般百姓使用talwar更大，
或許與經濟較富裕者體型通常會較大有關。
* 雖然talwar使用方式與歐洲軍刀很不同，
但當時的繪畫與D.A.Kinsley的著作中皆顯示，
許多19世紀甚至是18世紀駐印度的英國軍官因talwar優秀的性能而使用它，
並學習其與當時歐洲兵器相當不同的使用方式。
作者並提及talwar的使用方式反而較近似中世紀兵器。
